---
- name: package installation
  apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
  loop:
          - 'aptitude'
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'software-properties-common'  
