---
- include_tasks: "install_package.yml"
- include_tasks: "add_docker_key.yml"
- include_tasks: "add_docker_repository.yml"
- include_tasks: "install_docker.yml"
- include_tasks: "config.yml"
- include_tasks: "instal_python.yml"
- include_tasks: "config_daemon.yml"
- include_tasks: "pull_docker.yml"
- include_tasks: "create_containers.yml"  

